version: "3.3"

services:
  caddy:
    image: davidtca/caddy-discord:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - $PWD/caddy/Caddyfile-dev:/etc/caddy/Caddyfile
  nolocal:
    build: .