version: "3.3"

services:
  caddy:
    image: davidtca/caddy-discord:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
  nolocal:
    image: davidtca/nolocal
    container_name: nolocal
    environment:
      - DISCORD_TOKEN