version: "3.8"

services:
  caddy:
    image: davidtca/caddy-discord:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - $PWD/Caddyfile-dev:/etc/caddy/Caddyfile
  nolocal:
    build: .