spring:
  profiles:
    active: production
secrets:
  discord:
    token: ${DISCORD_TOKEN:dummy-token}
logging:
  path: /var/log

management:
  metrics:
    export:
      newrelic:
        api-key: ${INSIGHTS_KEY:dummy-key}
        account-id: 3326893