spring:
  profiles:
    active: production
logging:
  path: /var/log
  level:
    root: ERROR
    org.springframework: INFO
    com.datocal.nolocal: TRACE
discord:
  api:
    url: https://discord.com/api/v8/applications/
    secret: ${DISCORD_TOKEN:dummy-token}
    client-id: 899356200745984010