spring:
  profiles:
    active: production
secrets:
  discord:
    token: ${DISCORD_TOKEN:dummy-token}
logging:
  path: /var/log
  level:
    root: ERROR
    org.springframework: INFO
    com.datocal.nolocal: TRACE