name: Generate docs
on:
  workflow_dispatch:

jobs:
  BuildDocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
      - name: Build docs
        run: |
          cd docs
          npm install
          npm run build
          date >> build/runs.txt
      - name: Upload docs
        uses: actions/upload-artifact@v2.2.4
        with:
          path: docs/build/
      - name: Github Pages Deploy
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: ./docs/build/
          branch: docs
          token: ${{secrets.TOKEN_GITHUB}}
