name: Generate docs
on:
  workflow_dispatch:

jobs:
  BuildDocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
      - name: Build docs
        run: |
          pip install mkdocs
          mkdocs build
      - name: Upload docs
        uses: actions/upload-artifact@v2.2.4
        with:
          path: site/
          name: documentation
      - name: Github Pages Deploy
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: site/
          branch: docs
          token: ${{secrets.TOKEN_GITHUB}}
