name: Mutation Tests
on:
  workflow_dispatch:

jobs:
  Mutation-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@0.2.0
        with:
          version: 1.5.31
      - name: Mutation test run
        env: 
          spring.profiles.active: true
        run: | 
           chmod +x ./gradlew
           ./gradlew pitest
      - name: Publish Test Report
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'mutation-report'
          path: build/reports/pitest/*
