name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Full-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@0.2.0
        with:
          version: 1.5.31
      - name: Gradlew Check
        run: | 
           chmod +x ./gradlew
           ./gradlew --no-daemon check
      - name: Codecov coverage report upload
        uses: codecov/codecov-action@v2.1.0 
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      - name: Build Jar
        run: ./gradlew --no-daemon bootJar
      - name: Publish Jar
        uses: actions/upload-artifact@v2.2.4
        with:
          path: ./build/libs/*.jar
      - name: Install Oracle Cloud Infrastructure CLI
        uses: bytesbay/oci-cli-action@v1.0.2 
        with:
          user: ${{secrets.OCI_USER_OCID}}
          fingerprint: ${{secrets.OCI_FINGERPRINT}}
          tenancy: ${{secrets.OCI_TENANCY_OCID}}
          region: ${{secrets.OCI_REGION}}
          api_key: ${{secrets.OCI_KEY_FILE}}
