name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Full-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@0.2.0
        with:
          version: 1.5.31
      - name: Gradlew Check
        run: | 
           chmod +x ./gradlew
           ./gradlew check
      - name: Build Jar
        run: ./gradlew bootJar
      - name: Get Version Number
        run: echo "::set-env name=VERSION::$(./gradlew properties -q | grep "version:" | awk '{print $2}')"
      - name: Publish Jar
        run: echo nolocal-${{env.VERSION}}.jar
      - name: Deploy
        run: echo deploying!
